[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/images/*"
  to = "/ui/images/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/assets/*"
  to = "/ui/assets/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "http://65.1.50.127/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ui/*"
  to = "/ui/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
